spring:
  mvc:
    pathmatch:
      matching-strategy : ANT_PATH_MATCHER
  jpa:
    show-sql: true
  h2:
    console.enabled: true
  datasource:
    generate-unique-name: false
    name: demo
server:
  error:
    include-stacktrace: never
  mvc:
    cors:
      allow-credentials: false