spring:
  mvc:
    pathmatch:
      matching-strategy : ANT_PATH_MATCHER
  jpa:
    show-sql: true
  h2:
    console.enabled: true
  datasource:
    generate-unique-name: false
    name: demo
  boot:
    admin:
      client: 
        url: http://localhost:9080
        instance:
          metadata:
            tags:
              environment: dev
server:
  error:
    include-stacktrace: never
  mvc:
    cors:
      allow-credentials: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    greet: Good Morning
info:
  tags:
    environment: dev
